Update requirements.txt
user_agent version requirement was deleted in order to use the latest version and no longer have the following bug :

  File "/usr/local/lib/python3.12/site-packages/wrpy/core.py", line 49, in __init__
    self.user_agent = user_agent.generate_user_agent()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/user_agent/base.py", line 567, in generate_user_agent
    return generate_navigator(os=os, navigator=navigator,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/user_agent/base.py", line 521, in generate_navigator
 * Debug mode: on
Start:  2023-10-08 18:59:52.334254
    app = build_app_components(os_id, navigator_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/user_agent/base.py", line 344, in build_app_components
    build_version, build_id = get_firefox_build()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/user_agent/base.py", line 214, in get_firefox_build
    timedelta(seconds=randint(0, sec_range)))
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/random.py", line 312, in randrange
    istop = _index(stop)
            ^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer